name: rDamageIndicator
version: '${project.version}'
main: dev.rishon.rdamageindicator.Main
api-version: 1.19
authors: [ Rishon ]
description: Asynchronous Damage Indicator
website: https://rishon.systems
